name: sc_preprocess
channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - bioconductor-alevinqc
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-eisar
  - bioconductor-fishpond
  - bioconductor-genomicfeatures
  - bioconductor-rtracklayer
  - bioconductor-summarizedexperiment
  - bioconductor-tximeta
  - r-base>=4.0
  - r-ggplot2
  - r-optparse
  - r-reshape2
  
