name: sc_preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - bioconductor-annotationdbi=1.50.0
  - bioconductor-annotationfilter=1.12.0
  - bioconductor-annotationhub=2.20.0
  - bioconductor-biobase=2.48.0
  - bioconductor-biocfilecache=1.12.0
  - bioconductor-biocgenerics=0.34.0
  - bioconductor-biocparallel=1.22.0
  - bioconductor-biocversion=3.11.1
  - bioconductor-biomart=2.44.0
  - bioconductor-biostrings=2.56.0
  - bioconductor-bsgenome=1.56.0
  - bioconductor-delayedarray=0.14.0
  - bioconductor-edger=3.30.0
  - bioconductor-eisar=1.0.0
  - bioconductor-ensembldb=2.12.1
  - bioconductor-fishpond=1.4.0
  - bioconductor-genomeinfodb=1.24.0
  - bioconductor-genomeinfodbdata=1.2.3
  - bioconductor-genomicalignments=1.24.0
  - bioconductor-genomicfeatures=1.40.0
  - bioconductor-genomicranges=1.40.0
  - bioconductor-interactivedisplaybase=1.26.0
  - bioconductor-iranges=2.22.1
  - bioconductor-limma=3.44.1
  - bioconductor-protgenerics=1.20.0
  - bioconductor-qvalue=2.20.0
  - bioconductor-rhtslib=1.20.0
  - bioconductor-rsamtools=2.4.0
  - bioconductor-rtracklayer=1.48.0
  - bioconductor-s4vectors=0.26.0
  - bioconductor-summarizedexperiment=1.18.1
  - bioconductor-tximeta=1.6.3
  - bioconductor-tximport=1.16.0
  - bioconductor-xvector=0.28.0
  - bioconductor-zlibbioc=1.34.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2021.5.30
  - cairo=1.16.0
  - certifi=2021.5.30
  - curl=7.71.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gettext=0.19.8.1
  - glib=2.66.2
  - graphite2=1.3.13
  - gsl=2.6
  - harfbuzz=2.4.0
  - icu=64.2
  - jemalloc=5.2.1
  - jpeg=9d
  - krb5=1.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.2
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - ncurses=6.2
  - openssl=1.1.1k
  - pandoc=2.14.0.3
  - pango=1.42.4
  - pcre=8.44
  - pcre2=10.35
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.9.0
  - python_abi=3.9
  - r=4.0
  - r-abind=1.4_5
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.10
  - r-base=4.0.2
  - r-base64enc=0.1_3
  - r-bh=1.72.0_3
  - r-biocmanager=1.30.16
  - r-bit=4.0.4
  - r-bit64=4.0.5
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-bookdown=0.22
  - r-boot=1.3_25
  - r-class=7.3_17
  - r-cli=2.1.0
  - r-cluster=2.1.0
  - r-codetools=0.2_17
  - r-colorspace=2.0_2
  - r-commonmark=1.7
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-dbi=1.1.0
  - r-dbplyr=1.4.4
  - r-desc=1.3.0
  - r-digest=0.6.27
  - r-dplyr=1.0.2
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.1.0
  - r-fastmap=1.1.0
  - r-foreign=0.8_80
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-generics=0.0.2
  - r-ggplot2=3.3.5
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-gtools=3.9.2
  - r-highr=0.9
  - r-hms=0.5.3
  - r-htmltools=0.5.1.1
  - r-httpuv=1.6.1
  - r-httr=1.4.2
  - r-isoband=0.2.4
  - r-jsonlite=1.7.1
  - r-kernsmooth=2.23_17
  - r-knitr=1.33
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-later=1.2.0
  - r-lattice=0.20_41
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-locfit=1.5_9.4
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-matrixstats=0.57.0
  - r-memoise=1.1.0
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-nnet=7.3_14
  - r-openssl=1.4.3
  - r-pillar=1.4.6
  - r-pkgconfig=2.0.3
  - r-pkgload=1.2.1
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-progress=1.2.2
  - r-promises=1.2.0.1
  - r-purrr=0.3.4
  - r-r6=2.5.0
  - r-rappdirs=0.3.1
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rcurl=1.98_1.2
  - r-recommended=4.0
  - r-reshape2=1.4.4
  - r-rhpcblasctl=0.20_137
  - r-rlang=0.4.7
  - r-rmarkdown=2.9
  - r-rmdformats=1.0.2
  - r-rpart=4.1_15
  - r-rprojroot=2.0.2
  - r-rsqlite=2.2.1
  - r-rstudioapi=0.13
  - r-scales=1.1.1
  - r-shiny=1.5.0
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-spatial=7.3_12
  - r-stringi=1.4.6
  - r-stringr=1.4.0
  - r-survival=3.2_7
  - r-svmisc=1.1.4
  - r-sys=3.4
  - r-testthat=2.3.2
  - r-tibble=3.0.4
  - r-tidyselect=1.1.0
  - r-tinytex=0.32
  - r-utf8=1.1.4
  - r-vctrs=0.3.4
  - r-viridislite=0.4.0
  - r-withr=2.4.2
  - r-xfun=0.24
  - r-xml=3.99_0.3
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - readline=8.0
  - salmon=1.3.0
  - sed=4.8
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tbb=2020.2
  - tk=8.6.10
  - tktable=2.10
  - tzdata=2020d
  - wheel=0.35.1
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
