name: sc_preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-delayedarray
  - bioconductor-eisar
  - bioconductor-fishpond
  - bioconductor-genomicfeatures
  - bioconductor-rtracklayer
  - bioconductor-summarizedexperiment
  - bioconductor-tximeta
  - r-base>=4.0
