name: sc_preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex
  - _r-mutex
  - bioconductor-annotationdbi
  - bioconductor-annotationfilter
  - bioconductor-annotationhub
  - bioconductor-biobase
  - bioconductor-biocfilecache
  - bioconductor-biocgenerics
  - bioconductor-biocparallel
  - bioconductor-biocversion
  - bioconductor-biomart
  - bioconductor-biostrings
  - bioconductor-bsgenome
  - bioconductor-delayedarray
  - bioconductor-edger
  - bioconductor-eisar
  - bioconductor-ensembldb
  - bioconductor-fishpond
  - bioconductor-genomeinfodb
  - bioconductor-genomeinfodbdata
  - bioconductor-genomicalignments
  - bioconductor-genomicfeatures
  - bioconductor-genomicranges
  - bioconductor-interactivedisplaybase
  - bioconductor-iranges
  - bioconductor-limma
  - bioconductor-protgenerics
  - bioconductor-qvalue
  - bioconductor-rhtslib
  - bioconductor-rsamtools
  - bioconductor-rtracklayer
  - bioconductor-s4vectors
  - bioconductor-summarizedexperiment
  - bioconductor-tximeta
  - bioconductor-tximport
  - bioconductor-xvector
  - bioconductor-zlibbioc
  - bwidget
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - curl
  - fontconfig
  - freetype
  - fribidi
  - gettext
  - glib
  - graphite2
  - gsl
  - harfbuzz
  - icu
  - jemalloc
  - jpeg
  - krb5
  - libblas
  - libcblas
  - libcurl
  - libedit
  - libev
  - libffi
  - libglib
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - libssh2
  - libtiff
  - libuuid
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - make
  - multiqc
  - ncurses
  - openssl
  - pandoc
  - pango
  - pcre
  - pcre2
  - pip
  - pixman
  - pthread-stubs
  - python
  - python_abi
  - r
  - r-abind
  - r-askpass
  - r-assertthat
  - r-backports
  - r-base
  - r-base64enc
  - r-bh
  - r-biocmanager
  - r-bit
  - r-bit64
  - r-bitops
  - r-blob
  - r-bookdown
  - r-boot
  - r-class
  - r-cli
  - r-cluster
  - r-codetools
  - r-colorspace
  - r-commonmark
  - r-crayon
  - r-curl
  - r-dbi
  - r-dbplyr
  - r-desc
  - r-digest
  - r-dplyr
  - r-ellipsis
  - r-evaluate
  - r-fansi
  - r-farver
  - r-fastmap
  - r-foreign
  - r-formatr
  - r-futile.logger
  - r-futile.options
  - r-generics
  - r-ggplot2
  - r-glue
  - r-gtable
  - r-gtools
  - r-highr
  - r-hms
  - r-htmltools
  - r-httpuv
  - r-httr
  - r-isoband
  - r-jsonlite
  - r-kernsmooth
  - r-knitr
  - r-labeling
  - r-lambda.r
  - r-later
  - r-lattice
  - r-lazyeval
  - r-lifecycle
  - r-locfit
  - r-magrittr
  - r-markdown
  - r-mass
  - r-matrix
  - r-matrixstats
  - r-memoise
  - r-mgcv
  - r-mime
  - r-munsell
  - r-nlme
  - r-nnet
  - r-openssl
  - r-pillar
  - r-pkgconfig
  - r-pkgload
  - r-plogr
  - r-plyr
  - r-praise
  - r-prettyunits
  - r-progress
  - r-promises
  - r-purrr
  - r-r6
  - r-rappdirs
  - r-rcolorbrewer
  - r-rcpp
  - r-rcurl
  - r-recommended
  - r-reshape2
  - r-rhpcblasctl
  - r-rlang
  - r-rmarkdown
  - r-rmdformats
  - r-rpart
  - r-rprojroot
  - r-rsqlite
  - r-rstudioapi
  - r-scales
  - r-shiny
  - r-snow
  - r-sourcetools
  - r-spatial
  - r-stringi
  - r-stringr
  - r-survival
  - r-svmisc
  - r-sys
  - r-testthat
  - r-tibble
  - r-tidyselect
  - r-tinytex
  - r-utf8
  - r-vctrs
  - r-viridislite
  - r-withr
  - r-xfun
  - r-xml
  - r-xtable
  - r-yaml
  - r-zeallot
  - readline
  - salmon
  - sed
  - setuptools
  - sqlite
  - tbb
  - tk
  - tktable
  - tzdata
  - wheel
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
