# CI tests using GitHub Actions

name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  
jobs:
  
  #=======================================================================================================
  
  SC_PREPROCESS_CI_TESTS:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: INSTALL-NEXTFLOW
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      # full with docker
      - name: TEST-DOCKER_ALL
        run: NXF_VER=21.10.6 nextflow run main.nf -profile docker,test

      # only indexing, then exit
      - name: TEST-DOCKER_IDX_ONLY
        run: NXF_VER=21.10.6 nextflow run main.nf -profile docker,test --idx_only

      # provide an existing index 
      - name: TEST-DOCKER_IDX_PROVIDED 
        run: NXF_VER=21.10.6 nextflow run main.nf -profile docker,test --idx $(realpath test/idx_test/idx_gentrome/)

      - name: Commit software versions
        run: |
          git config --global user.name 'atpoint'
          git config --global user.email 'atpoint@users.noreply.github.com'
          mkdir -p misc && cp sc_preprocess_results/pipeline_info/*.txt misc/
          git add misc/*.txt
          if (( $(git status -s | grep -c 'misc/') > 0 )); then 
            git commit -am "update software version and command line reports"
            git push -f
          fi        