# CI tests using GitHub Actions

name: CI

on:
  # trigger on push
  push:
    # to all branches
    branches:
      - '**'
    # ignore LICENSE, all .ignore and markdown files
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  pull_request:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  #=======================================================================================================
  
  # Test via Docker and conda:
  docker_and_conda:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: TEST-DOCKER
        run: NXF_VER=21.10.6 nextflow run main.nf -profile docker,test

      - name: TEST-CONDA
        run: NXF_VER=21.10.6 nextflow run main.nf -profile conda,test

      - uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.3
    
      - name: TEST-SINGULARITY
        run: NXF_VER=21.10.6 nextflow run main.nf -profile singularity,test  