# CI tests using GitHub Actions

name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE
  
jobs:
  
  #=======================================================================================================
  
  SC_PREPROCESS_CI_TESTS:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: INSTALL-NEXTFLOW
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/

      - name: TEST-NO_FB
        run: NXF_VER=22.10.4 nextflow run main.nf -profile docker,test --samplesheet $(realpath test/samplesheet_nofb.csv)

      - name: TEST-FULL
        run: NXF_VER=22.10.4 nextflow run main.nf -profile docker,test --features_file $(realpath test/hto.tsv) --samplesheet $(realpath test/samplesheet.csv)

      - name: Commit software versions
        run: |
          git config --global user.name 'atpoint'
          git config --global user.email 'atpoint@users.noreply.github.com'
          mkdir -p misc && cp sc_preprocess_results/pipeline_info/*.txt misc/
          git add misc/*.txt
          if (( $(git status -s | grep -c 'misc/') > 0 )); then 
            git commit -am "update software version and command line reports"
            git push -f
          fi        
